package json.tokenizer.tokens;

public enum TokenTypes {
    CURLY_BRACKET_OPEN, CURLY_BRACKET_CLOSE, STRING, NUMBER, TRUE, FALSE, NULL, COLON, COMMA, SQAURE_BRACKET_OPEN,
    SQAURE_BRACKET_CLOSE, END_OF_FILE
}